// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ChatRoomApp.Models
{
    public partial class ChartRoomAppContext : DbContext
    {
        public ChartRoomAppContext()
        {
        }

        public ChartRoomAppContext(DbContextOptions<ChartRoomAppContext> options)
            : base(options)
        {
        }

        public virtual DbSet<users> users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<users>(entity =>
            {
                entity.HasKey(e => e.user_id)
                    .HasName("PK__users__B9BE370FBAA0250A");

                entity.Property(e => e.created_datetime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.user_name)
                    .IsRequired()
                    .HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}