// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatRoomApp.Models
{
    public partial class chatrooms
    {
        public int room_id { get; set; }
        public string room_name { get; set; }
        public string room_description { get; set; }
        public string room_type { get; set; }
        public string room_code { get; set; }
        public string user_name { get; set; }
    }
}