// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ChatRoomApp.Models
{
    public partial class users
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public DateTime? created_datetime { get; set; }
    }
}